### ISSUE TITLE
CC2531 Firmware

### ISSUE THREAD

**Issue by mtornblad** [andrewdodd/ccsniffpiper#8]
Hello,

Would like to try this tool but my CC2531 appear with different USB-id (idVendor=0451, idProduct=16a8), what is the correct firmware to use with this tool? If you could add it to the github repository would be appreciated!

Best Regards,
Mattias Törnblad

**Comment by andrewdodd** [comment]
Hi Mattias,

It has been a year or two since I have used this tool (and unfortunately I don't have any CC2531 sniffers any more).

As I recall, there were a few items you had to deal with to get these tools running, including:
 - getting the correct firmware etc on the EMK
 - making sure the protocol was correct (TI would occasionally change it, and the documentation was getting more and more vague).

It would be worth trying to see if this project works for you first (it is a bit simpler): https://github.com/andrewdodd/pyCCSniffer

I never got around to packaging it properly, but the steps were something like:
> git clone https://github.com/andrewdodd/pyCCSniffer
> cd pyCCSniffer
> mkvirtualenv  (or however you need to do this)
> install 'pyusb >= 1.0' -> which can sometimes be a real pain
> python pyCCSniffer.py

I will get hold of some of these bits of hardware in about 2 months, so I might be able to help a little more then?

Sorry, and good luck,
Andrew
